/**
 * Stripe Checkout Handler
 * Creates checkout sessions for website packages with optional discount codes
 */

const stripe = require('stripe')(process.env.STRIPE_SECRET_KEY);

if (!process.env.STRIPE_SECRET_KEY) {
  throw new Error('STRIPE_SECRET_KEY environment variable is required');
}

const PACKAGES = {
  silver: { name: 'Silver - AI Website', price: 99500, priceId: 'price_1QaHxK2NFW59QiEi6qJ7kL9m' }, // £995
  gold: { name: 'Gold - AI + Booking Bot', price: 149500, priceId: 'price_1QaHxK2NFW59QiEi8nO2pQ5r' }, // £1,495
  platinum: { name: 'Platinum - All-in-One Sales Machine', price: 199500, priceId: 'price_1QaHxK2NFW59QiEi9sT3vW8s' } // £1,995
};

// Store for BDM discount codes (in production: database)
const discountCodes = new Map();

// Default discount codes (will be populated by BDM dashboard)
const DEFAULT_CODES = [
  // These would be generated by the BDM dashboard
  // Format: { code: 'BDMABC123', price: 49500, maxUses: 1, usedCount: 0, expiry: '2026-05-31' }
];

/**
 * Validate and apply discount code
 */
function validateDiscountCode(code, packagePrice) {
  if (!code) return { valid: false, discount: 0, finalPrice: packagePrice };
  
  const discountRecord = discountCodes.get(code.toUpperCase());
  
  if (!discountRecord) {
    return { valid: false, error: 'Code not found', discount: 0, finalPrice: packagePrice };
  }
  
  // Check expiry
  if (new Date(discountRecord.expiry) < new Date()) {
    return { valid: false, error: 'Code expired', discount: 0, finalPrice: packagePrice };
  }
  
  // Check max uses
  if (discountRecord.maxUses > 0 && discountRecord.usedCount >= discountRecord.maxUses) {
    return { valid: false, error: 'Code limit reached', discount: 0, finalPrice: packagePrice };
  }
  
  // Code is valid
  const discount = packagePrice - discountRecord.price;
  return {
    valid: true,
    code: code.toUpperCase(),
    originalPrice: packagePrice,
    finalPrice: discountRecord.price,
    discount: discount,
    percentOff: Math.round((discount / packagePrice) * 100)
  };
}

/**
 * Create Stripe Checkout Session
 */
async function createCheckoutSession(req, res) {
  try {
    const { package: pkg, discountCode, email, successUrl, cancelUrl } = req.body;
    
    if (!pkg || !PACKAGES[pkg]) {
      return res.status(400).json({ error: 'Invalid package' });
    }
    
    if (!email) {
      return res.status(400).json({ error: 'Email required' });
    }
    
    const packageData = PACKAGES[pkg];
    const validation = validateDiscountCode(discountCode, packageData.price);
    
    // Create checkout session
    const sessionConfig = {
      payment_method_types: ['card'],
      mode: 'payment',
      customer_email: email,
      line_items: [
        {
          price_data: {
            currency: 'gbp',
            product_data: {
              name: `${packageData.name} Website Package`,
              description: `Professional website package: ${packageData.name} tier`,
              metadata: {
                package: pkg,
                discountCode: discountCode || null
              }
            },
            unit_amount: validation.finalPrice
          },
          quantity: 1
        }
      ],
      success_url: successUrl || 'https://installsmart.ai/websites/success.html',
      cancel_url: cancelUrl || 'https://installsmart.ai/websites/',
      metadata: {
        package: pkg,
        discountCode: discountCode || null,
        originalPrice: packageData.price,
        finalPrice: validation.finalPrice,
        discount: validation.discount
      }
    };
    
    const session = await stripe.checkout.sessions.create(sessionConfig);
    
    // Mark code as used if valid
    if (validation.valid && discountCode) {
      const record = discountCodes.get(discountCode.toUpperCase());
      if (record) record.usedCount += 1;
    }
    
    res.json({
      sessionId: session.id,
      url: session.url,
      package: pkg,
      packageName: packageData.name,
      originalPrice: packageData.price / 100,
      finalPrice: validation.finalPrice / 100,
      discount: validation.discount / 100,
      discountPercentage: validation.percentOff,
      email: email
    });
  } catch (error) {
    console.error('Checkout error:', error);
    res.status(500).json({ error: error.message });
  }
}

/**
 * Validate discount code (for frontend)
 */
function validateCode(req, res) {
  try {
    const { code, package: pkg } = req.query;
    
    if (!code || !pkg) {
      return res.status(400).json({ error: 'Code and package required' });
    }
    
    if (!PACKAGES[pkg]) {
      return res.status(400).json({ error: 'Invalid package' });
    }
    
    const packagePrice = PACKAGES[pkg].price;
    const validation = validateDiscountCode(code, packagePrice);
    
    res.json({
      valid: validation.valid,
      code: code.toUpperCase(),
      discount: validation.discount ? (validation.discount / 100).toFixed(2) : null,
      finalPrice: validation.finalPrice ? (validation.finalPrice / 100).toFixed(2) : null,
      discountPercentage: validation.percentOff || 0,
      error: validation.error || null
    });
  } catch (error) {
    console.error('Validation error:', error);
    res.status(500).json({ error: error.message });
  }
}

/**
 * Add discount code (from BDM dashboard)
 */
function addDiscountCode(req, res) {
  try {
    const { code, price, maxUses, expiry, secret } = req.body;
    
    // Simple auth: check secret key
    if (secret !== process.env.BDM_SECRET || !process.env.BDM_SECRET) {
      return res.status(401).json({ error: 'Unauthorized' });
    }
    
    if (!code || price === undefined) {
      return res.status(400).json({ error: 'Code and price required' });
    }
    
    if (price < 49500 || price > 99500) {
      return res.status(400).json({ error: 'Price must be £495–£995' });
    }
    
    discountCodes.set(code.toUpperCase(), {
      code: code.toUpperCase(),
      price: price,
      maxUses: maxUses || 0,
      usedCount: 0,
      expiry: expiry || new Date(Date.now() + 6 * 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
    });
    
    res.json({
      success: true,
      code: code.toUpperCase(),
      price: (price / 100).toFixed(2),
      discount: ((99500 - price) / 100).toFixed(2)
    });
  } catch (error) {
    console.error('Add code error:', error);
    res.status(500).json({ error: error.message });
  }
}

/**
 * Webhook: Handle Stripe events
 */
async function handleWebhook(req, res) {
  const sig = req.headers['stripe-signature'];
  const secret = process.env.STRIPE_WEBHOOK_SECRET;
  
  try {
    const event = stripe.webhooks.constructEvent(req.body, sig, secret);
    
    switch (event.type) {
      case 'checkout.session.completed':
        const session = event.data.object;
        console.log('✅ Payment completed:', {
          sessionId: session.id,
          email: session.customer_email,
          amount: session.amount_total,
          metadata: session.metadata
        });
        
        // TODO: Record to CRM/database
        // TODO: Send confirmation email
        // TODO: Create customer account
        break;
        
      case 'checkout.session.expired':
        console.log('⏱️ Checkout expired:', event.data.object.id);
        break;
    }
    
    res.json({ received: true });
  } catch (error) {
    console.error('Webhook error:', error);
    res.status(400).send(`Webhook Error: ${error.message}`);
  }
}

module.exports = {
  createCheckoutSession,
  validateCode,
  addDiscountCode,
  handleWebhook,
  validateDiscountCode
};
